### ISSUE TITLE
haha imagine putting javadoc comments on one line without actual javadoc elements

### ISSUE THREAD

**Issue by Sei4or** [mount-si-robotics/RoboticsOutreach#1]
yes

**Comment by Sei4or** [comment]
pls @CalvinSprouse

**Comment by FernSprouse** [comment]
**/ You can delete them **/

**Comment by Sei4or** [comment]
This issue was closed at 11:49 AM (6 minutes ago). If you would like to contact the issuer please re-open the issue. #69
